version: '3'
services:
 postgresql-replication:
  image: 'postgres:15'
  network_mode: 'host'
  entrypoint: /etc/postgresql/entrypoint.sh
  volumes:
    - ./data:/var/lib/postgresql/data
    - ./entrypoint.sh:/etc/postgresql/entrypoint.sh
    - ./config/pgpass:/var/lib/postgresql/.pgpass
  env_file:
    - ./config/docker.env
